# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import os
import warnings  # 🧪
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from wt_contracts import validate as _validate
from wt_task import task
from wt_task.testing import create_func_magicmock  # 🧪

from .. import metadata as _metadata

get_events = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_events",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import (
    extract_value_from_json_column as extract_value_from_json_column,
)

process_events_details = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="process_events_details",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.transformation import (
    apply_reloc_coord_filter as apply_reloc_coord_filter,
)
from ecoscope.platform.tasks.transformation import (
    drop_column_prefix as drop_column_prefix,
)
from ecoscope.platform.tasks.transformation import (
    extract_spatial_grouper_feature_group_names as extract_spatial_grouper_feature_group_names,
)
from ecoscope.platform.tasks.transformation import (
    normalize_json_column as normalize_json_column,
)

get_spatial_features_group = create_func_magicmock(  # 🧪
    anchor="ecoscope.platform.tasks.io",  # 🧪
    func_name="get_spatial_features_group",  # 🧪
)  # 🧪
from ecoscope.platform.tasks.analysis import (
    calculate_feature_density as calculate_feature_density,
)
from ecoscope.platform.tasks.config import (
    call_meshgrid_from_combined_params as call_meshgrid_from_combined_params,
)
from ecoscope.platform.tasks.config import concat_string_vars as concat_string_vars
from ecoscope.platform.tasks.config import (
    default_if_string_is_empty as default_if_string_is_empty,
)
from ecoscope.platform.tasks.config import (
    get_opacity_from_combined_params as get_opacity_from_combined_params,
)
from ecoscope.platform.tasks.config import (
    set_density_grid_options as set_density_grid_options,
)
from ecoscope.platform.tasks.config import (
    set_optional_string_var as set_optional_string_var,
)
from ecoscope.platform.tasks.config import set_string_var as set_string_var
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import create_polygon_layer as create_polygon_layer
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import all_geometry_are_none as all_geometry_are_none
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_spatial_index as add_spatial_index,
)
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    drop_nan_values_by_column as drop_nan_values_by_column,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope.platform.tasks.transformation import (
    resolve_spatial_feature_groups_for_spatial_groupers as resolve_spatial_feature_groups_for_spatial_groupers,
)
from ecoscope.platform.tasks.transformation import sort_values as sort_values


def main(params: dict[str, Any], validate_params_schema: bool = True):
    warnings.warn("This test script should not be used in production!")  # 🧪

    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_format="%d %b %Y %H:%M:%S %Z", **(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    get_events_data = (
        task(get_events)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("get_events_data")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            event_columns=[
                "id",
                "time",
                "event_type",
                "event_category",
                "reported_by",
                "serial_number",
                "event_details",
                "geometry",
            ],
            include_null_geometry=False,
            raise_on_empty=False,
            include_details=True,
            include_updates=False,
            include_related_events=False,
            include_display_values=True,
            force_point_geometry=True,
            **(params.get("get_events_data") or {}),
        )
        .call()
    )

    convert_events_tz = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_events_tz")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=get_events_data,
            timezone=get_timezone,
            columns=["time"],
            auto_detect=False,
            **(params.get("convert_events_tz") or {}),
        )
        .call()
    )

    extract_reported_by = (
        task(extract_value_from_json_column)
        .validate()
        .set_task_instance_id("extract_reported_by")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_events_tz,
            column_name="reported_by",
            field_name_options=["name"],
            output_type="str",
            output_column_name="reported_by_name",
            **(params.get("extract_reported_by") or {}),
        )
        .call()
    )

    process_event_details = (
        task(process_events_details)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("process_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=extract_reported_by,
            client=er_client_name,
            map_to_titles=True,
            ordered=True,
            **(params.get("process_event_details") or {}),
        )
        .call()
    )

    normalize_event_details = (
        task(normalize_json_column)
        .validate()
        .set_task_instance_id("normalize_event_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=process_event_details,
            column="event_details",
            skip_if_not_exists=True,
            sort_columns=False,
            **(params.get("normalize_event_details") or {}),
        )
        .call()
    )

    drop_event_details_prefix = (
        task(drop_column_prefix)
        .validate()
        .set_task_instance_id("drop_event_details_prefix")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=normalize_event_details,
            prefix="event_details__",
            duplicate_strategy="suffix",
            **(params.get("drop_event_details_prefix") or {}),
        )
        .call()
    )

    convert_event_details_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_event_details_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=drop_event_details_prefix,
            timezone=get_timezone,
            columns=[],
            auto_detect=True,
            **(params.get("convert_event_details_timezone") or {}),
        )
        .call()
    )

    filter_events = (
        task(apply_reloc_coord_filter)
        .validate()
        .set_task_instance_id("filter_events")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=convert_event_details_timezone,
            roi_gdf=None,
            roi_name=None,
            reset_index=True,
            **(params.get("filter_events") or {}),
        )
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("groupers") or {}))
        .call()
    )

    spatial_group_ids = (
        task(extract_spatial_grouper_feature_group_names)
        .validate()
        .set_task_instance_id("spatial_group_ids")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=groupers, **(params.get("spatial_group_ids") or {}))
        .call()
    )

    fetch_all_spatial_feature_groups = (
        task(get_spatial_features_group)
        # 🧪 validation omitted for mocked IO task (returns pre-loaded example data)
        .set_task_instance_id("fetch_all_spatial_feature_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            **(params.get("fetch_all_spatial_feature_groups") or {}),
        )
        .map(argnames=["spatial_features_group_name"], argvalues=spatial_group_ids)
    )

    resolved_groupers = (
        task(resolve_spatial_feature_groups_for_spatial_groupers)
        .validate()
        .set_task_instance_id("resolved_groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=groupers,
            spatial_feature_groups=fetch_all_spatial_feature_groups,
            **(params.get("resolved_groupers") or {}),
        )
        .call()
    )

    events_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("events_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=filter_events,
            time_col="time",
            groupers=resolved_groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("events_add_temporal_index") or {}),
        )
        .call()
    )

    events_add_spatial_index = (
        task(add_spatial_index)
        .validate()
        .set_task_instance_id("events_add_spatial_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=events_add_temporal_index,
            groupers=resolved_groupers,
            **(params.get("events_add_spatial_index") or {}),
        )
        .call()
    )

    set_map_title = (
        task(set_string_var)
        .validate()
        .set_task_instance_id("set_map_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="Event Sum Map", **(params.get("set_map_title") or {}))
        .call()
    )

    base_map_defs = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_map_defs") or {}))
        .call()
    )

    split_event_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_event_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=events_add_spatial_index,
            groupers=resolved_groupers,
            **(params.get("split_event_groups") or {}),
        )
        .call()
    )

    agg_column = (
        task(set_optional_string_var)
        .validate()
        .set_task_instance_id("agg_column")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("agg_column") or {}))
        .call()
    )

    density_grid_options = (
        task(set_density_grid_options)
        .validate()
        .set_task_instance_id("density_grid_options")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(intersecting_only=False, **(params.get("density_grid_options") or {}))
        .call()
    )

    heatmap_opacity = (
        task(get_opacity_from_combined_params)
        .validate()
        .set_task_instance_id("heatmap_opacity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            combined_params=density_grid_options,
            **(params.get("heatmap_opacity") or {}),
        )
        .call()
    )

    events_meshgrid = (
        task(call_meshgrid_from_combined_params)
        .validate()
        .set_task_instance_id("events_meshgrid")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            aoi=events_add_spatial_index,
            combined_params=density_grid_options,
            **(params.get("events_meshgrid") or {}),
        )
        .call()
    )

    grouped_event_density = (
        task(calculate_feature_density)
        .validate()
        .set_task_instance_id("grouped_event_density")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            meshgrid=events_meshgrid,
            geometry_type="point",
            sum_column=agg_column,
            **(params.get("grouped_event_density") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_event_groups)
    )

    esm_sorted = (
        task(sort_values)
        .validate()
        .set_task_instance_id("esm_sorted")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="density",
            ascending=True,
            na_position="last",
            **(params.get("esm_sorted") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=grouped_event_density)
    )

    esm_drop_nan = (
        task(drop_nan_values_by_column)
        .validate()
        .set_task_instance_id("esm_drop_nan")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="density", **(params.get("esm_drop_nan") or {}))
        .mapvalues(argnames=["df"], argvalues=esm_sorted)
    )

    esm_classify = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("esm_classify")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density",
            output_column_name="density_bins",
            classification_options={"scheme": "equal_interval", "k": 10},
            label_options={"label_ranges": True, "label_decimals": 0},
            **(params.get("esm_classify") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=esm_drop_nan)
    )

    esm_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("esm_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="density_bins",
            colormap="RdYlGn_r",
            output_column_name="density_colormap",
            **(params.get("esm_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=esm_classify)
    )

    esm_total_label = (
        task(default_if_string_is_empty)
        .validate()
        .set_task_instance_id("esm_total_label")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            value=agg_column, default="Total", **(params.get("esm_total_label") or {})
        )
        .call()
    )

    esm_legend_title = (
        task(concat_string_vars)
        .validate()
        .set_task_instance_id("esm_legend_title")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            values=[esm_total_label, " per Grid Cell"],
            **(params.get("esm_legend_title") or {}),
        )
        .call()
    )

    esm_rename = (
        task(map_columns)
        .validate()
        .set_task_instance_id("esm_rename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            drop_columns=[],
            retain_columns=[],
            rename_columns={"density": esm_total_label},
            raise_if_not_found=True,
            **(params.get("esm_rename") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=esm_colormap)
    )

    esm_layer = (
        task(create_polygon_layer)
        .validate()
        .set_task_instance_id("esm_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
                all_geometry_are_none,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "density_colormap",
                "get_line_width": 0,
                "opacity": heatmap_opacity,
            },
            legend={"label_column": "density_bins", "color_column": "density_colormap"},
            tooltip_columns=[esm_total_label],
            **(params.get("esm_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=esm_rename)
    )

    esm_ecomap = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("esm_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "title": esm_legend_title,
                "format_title": False,
                "placement": "bottom-right",
            },
            static=False,
            max_zoom=20,
            widget_id=set_map_title,
            **(params.get("esm_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers"], argvalues=esm_layer)
    )

    esm_html = (
        task(persist_text)
        .validate()
        .set_task_instance_id("esm_html")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="event_sum_map",
            **(params.get("esm_html") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=esm_ecomap)
    )

    esm_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("esm_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title=set_map_title, **(params.get("esm_widget") or {}))
        .map(argnames=["view", "data"], argvalues=esm_html)
    )

    esm_widget_merged = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("esm_widget_merged")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=esm_widget, **(params.get("esm_widget_merged") or {}))
        .call()
    )

    event_sum_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("event_sum_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[esm_widget_merged],
            groupers=resolved_groupers,
            time_range=time_range,
            **(params.get("event_sum_dashboard") or {}),
        )
        .call()
    )

    return event_sum_dashboard
